steps:
  # Step 1: Build the Docker image using the backend folder context
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA', 
      '-f', 'backend/Dockerfile', 
      './backend'
    ]
    id: 'Build'

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA'
    ]
    id: 'Push'

  # Step 3: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args: [
      'run', 'services', 'update', '$_SERVICE_NAME',
      '--platform=managed',
      '--image=$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA',
      '--region=$_DEPLOY_REGION',
      '--quiet'
    ]
    id: 'Deploy'
    entrypoint: 'gcloud'

images:
  - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _DEPLOY_REGION: europe-west1
  _AR_HOSTNAME: europe-west1-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  _SERVICE_NAME: python-gcp-app